# Generated by Django 4.1 on 2022-08-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_forename", models.CharField(max_length=30)),
                ("doc_surname", models.CharField(max_length=30)),
                (
                    "doc_insurance",
                    models.CharField(
                        choices=[
                            ("Cigna", "Cigna"),
                            ("BUPA", "BUPA"),
                            ("Aviva", "Aviva"),
                            ("Cignet", "Cignet"),
                            ("Vitality", "Vitality"),
                            ("WPA", "WPA"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Specialties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("Depression", "Depression"),
                            ("OCD", "OCD"),
                            ("Anxiety", "Anxiety"),
                            ("PTSD", "PTSD"),
                            ("Schizophrenia", "Schizophrenia"),
                            ("Bulimia", "Bulimia"),
                            ("Bipolar_disorder", "Bipolar disorder"),
                            ("BPD", "BPD"),
                            ("Postpartum_depression", "Postpartum depression"),
                        ],
                        max_length=100,
                    ),
                ),
                ("doctors", models.ManyToManyField(to="directory.doctor")),
            ],
        ),
    ]
